import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  AlertTriangle, Bell, BellRing, CheckCheck, CheckCircle2, Info, Megaphone, Sparkles, Target, Trash2, TrendingUp, Wallet,
} from 'lucide-react';

import PageHeader from '../components/ui/PageHeader.jsx';
import Button from '../components/ui/Button.jsx';
import { Card } from '../components/ui/Card.jsx';
import { Badge, Segmented } from '../components/ui/Primitives.jsx';
import { EmptyState, ErrorState, Skeleton } from '../components/ui/Feedback.jsx';
import { ConfirmDialog } from '../components/ui/Modal.jsx';
import { announcementApi, notificationApi } from '../services/endpoints.js';
import { useApi, useApiAction } from '../hooks/useApi.js';
import { useToast } from '../context/ToastContext.jsx';
import { formatRelative } from '../utils/format.js';

const TYPE_ICONS = {
  budget_warning: AlertTriangle,
  budget_exceeded: AlertTriangle,
  large_transaction: TrendingUp,
  duplicate_transaction: Info,
  savings_milestone: Target,
  goal_completed: CheckCircle2,
  recurring: Wallet,
  import: Wallet,
  insight: Sparkles,
  welcome: Sparkles,
};

const SEVERITY_TONE = { danger: 'danger', warning: 'warning', success: 'success', info: 'brand' };

export default function Notifications() {
  const toast = useToast();
  const [filter, setFilter] = useState('all');
  const [confirmClear, setConfirmClear] = useState(false);

  const { data, isLoading, error, reload, refresh } = useApi(() => notificationApi.list(), { deps: [] });
  const { data: announcementData, refresh: refreshAnnouncements } = useApi(() => announcementApi.list(), { deps: [] });

  const markReadAction = useApiAction((id) => notificationApi.markRead(id), {
    onSuccess: () => {
      refresh();
      window.dispatchEvent(new CustomEvent('cc:notifications-changed'));
    },
    onError: (err) => toast.fromError(err, 'Could not mark that notification as read'),
  });

  const markAllAction = useApiAction(() => notificationApi.markAllRead(), {
    onSuccess: (response) => {
      toast.success(response.message || 'All notifications marked as read');
      refresh();
      window.dispatchEvent(new CustomEvent('cc:notifications-changed'));
    },
    onError: (err) => toast.fromError(err, 'Could not mark everything as read'),
  });

  const dismissAction = useApiAction((id) => notificationApi.dismiss(id), {
    onSuccess: () => {
      refresh();
      window.dispatchEvent(new CustomEvent('cc:notifications-changed'));
    },
    onError: (err) => toast.fromError(err, 'Could not dismiss that notification'),
  });

  const clearAction = useApiAction(() => notificationApi.clearRead(), {
    onSuccess: (response) => {
      toast.success(response.message || 'Read notifications cleared');
      setConfirmClear(false);
      refresh();
      window.dispatchEvent(new CustomEvent('cc:notifications-changed'));
    },
    onError: (err) => toast.fromError(err, 'Could not clear the notifications'),
  });

  const testAction = useApiAction(() => notificationApi.sendTest(), {
    onSuccess: () => {
      toast.success('Test notification created', { description: 'It appears at the top of this list.' });
      refresh();
      window.dispatchEvent(new CustomEvent('cc:notifications-changed'));
    },
    onError: (err) => toast.fromError(err, 'Could not send a test notification'),
  });

  const notifications = data?.notifications || [];
  const unread = data?.unread || 0;

  const visible = useMemo(() => {
    if (filter === 'unread') return notifications.filter((item) => !item.read);
    if (filter === 'alerts') return notifications.filter((item) => ['budget_warning', 'budget_exceeded', 'large_transaction'].includes(item.type));
    return notifications;
  }, [notifications, filter]);

  const grouped = useMemo(() => {
    const map = {};
    visible.forEach((item) => {
      const bucket = item.link?.startsWith('/budgets')
        ? 'Budgets'
        : item.link?.startsWith('/goals')
          ? 'Goals'
          : ['insight', 'tip'].includes(item.type) || item.link?.startsWith('/insights')
            ? 'Insights'
            : 'Other';
      map[bucket] = [...(map[bucket] || []), item];
    });
    return map;
  }, [visible]);

  const order = ['Budgets', 'Goals', 'Insights', 'Other'];

  return (
    <>
      <PageHeader
        title="Notifications"
        description="Budget alerts, savings milestones, recurring entries and campus announcements — every item is generated by a real event."
        crumbs={[{ label: 'Notifications' }]}
        icon={Bell}
        actions={
          <>
            <Button
              variant="secondary"
              size="sm"
              icon={BellRing}
              loading={testAction.isRunning}
              onClick={() => testAction.run()}
            >
              Send test
            </Button>
            <Button
              variant="secondary"
              size="sm"
              icon={CheckCheck}
              loading={markAllAction.isRunning}
              disabled={unread === 0}
              onClick={() => markAllAction.run()}
            >
              Mark all read
            </Button>
            <Button
              variant="ghost"
              size="sm"
              icon={Trash2}
              className="text-rose-500"
              disabled={!notifications.some((item) => item.read)}
              onClick={() => setConfirmClear(true)}
            >
              Clear read
            </Button>
          </>
        }
      />

      <Card className="mb-4 flex flex-wrap items-center justify-between gap-3 p-3.5">
        <Segmented
          ariaLabel="Filter notifications"
          value={filter}
          onChange={setFilter}
          options={[
            { value: 'all', label: `All (${notifications.length})` },
            { value: 'unread', label: `Unread (${unread})` },
            { value: 'alerts', label: 'Alerts' },
          ]}
        />
        {unread > 0 && <Badge tone="danger">{unread} unread</Badge>}
      </Card>

      {isLoading ? (
        <div className="space-y-3">
          {Array.from({ length: 5 }).map((_, index) => <Skeleton key={index} className="h-20 rounded-2xl" />)}
        </div>
      ) : error ? (
        <Card><ErrorState error={error} onRetry={reload} /></Card>
      ) : visible.length === 0 ? (
        <Card>
          <EmptyState
            icon={Bell}
            title={filter === 'unread' ? 'No unread notifications' : 'Nothing here yet'}
            description={
              filter === 'unread'
                ? 'You are all caught up. Alerts appear automatically when a budget is close to its cap or a transaction looks unusual.'
                : 'Log transactions and set budget caps — alerts and milestones will show up here as they happen.'
            }
            actionLabel="Back to dashboard"
            onAction={undefined}
            secondaryAction={<Link to="/dashboard" className="cc-btn-primary">Open dashboard</Link>}
          />
        </Card>
      ) : (
        <div className="space-y-5">
          {order.filter((bucket) => grouped[bucket]?.length).map((bucket) => (
            <section key={bucket} aria-labelledby={`notif-${bucket}`}>
              <h2 id={`notif-${bucket}`} className="mb-2.5 text-xs font-semibold uppercase tracking-wide text-ink-soft">
                {bucket} · {grouped[bucket].length}
              </h2>
              <ul className="space-y-2.5">
                {grouped[bucket].map((item) => {
                  const Icon = TYPE_ICONS[item.type] || Bell;
                  return (
                    <li key={item._id || item.id}>
                      <Card
                        className={`flex flex-col gap-3 p-4 transition sm:flex-row sm:items-center ${
                          item.read ? '' : 'border-brand-500/35 bg-brand-500/[.04]'
                        }`}
                      >
                        <span
                          className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${
                            item.severity === 'danger'
                              ? 'bg-rose-500/14 text-rose-500'
                              : item.severity === 'warning'
                                ? 'bg-amber-500/14 text-amber-500'
                                : item.severity === 'success'
                                  ? 'bg-mint-500/14 text-mint-600'
                                  : 'bg-brand-500/14 text-brand-500'
                          }`}
                        >
                          <Icon className="h-4 w-4" aria-hidden="true" />
                        </span>

                        <div className="min-w-0 flex-1">
                          <p className="flex flex-wrap items-center gap-2 text-sm font-semibold text-ink">
                            {item.title}
                            {!item.read && <span className="h-2 w-2 rounded-full bg-brand-500" aria-label="Unread" />}
                            <Badge tone={SEVERITY_TONE[item.severity] || 'neutral'}>{item.severity}</Badge>
                          </p>
                          <p className="mt-1 text-xs leading-relaxed text-ink-muted">{item.message}</p>
                          <p className="mt-1 text-2xs text-ink-soft">
                            {formatRelative(item.createdAt || item.updatedAt)}
                            {item.read && item.readAt ? ` · read ${formatRelative(item.readAt)}` : ''}
                          </p>
                        </div>

                        <div className="flex shrink-0 items-center gap-1.5">
                          {item.link && (
                            <Link to={item.link} className="cc-btn-secondary cc-btn-sm" onClick={() => !item.read && markReadAction.run(item._id || item.id)}>
                              Open
                            </Link>
                          )}
                          {!item.read && (
                            <Button
                              variant="ghost"
                              size="sm"
                              icon={CheckCheck}
                              onClick={() => markReadAction.run(item._id || item.id)}
                            >
                              Read
                            </Button>
                          )}
                          <Button
                            variant="ghost"
                            size="icon-sm"
                            className="text-rose-500"
                            icon={Trash2}
                            aria-label="Dismiss notification"
                            onClick={() => dismissAction.run(item._id || item.id)}
                          />
                        </div>
                      </Card>
                    </li>
                  );
                })}
              </ul>
            </section>
          ))}
        </div>
      )}

      {/* ── Campus announcements (admin published) ─────────────────── */}
      <section className="mt-8" aria-labelledby="announcements">
        <div className="mb-2.5 flex items-center justify-between">
          <h2 id="announcements" className="text-xs font-semibold uppercase tracking-wide text-ink-soft">
            Campus updates
          </h2>
          <Button variant="ghost" size="sm" onClick={() => refreshAnnouncements()}>Refresh</Button>
        </div>

        {!announcementData?.announcements?.length ? (
          <Card className="p-4 text-xs text-ink-soft">
            No announcements published by the campus administrator yet. When one is published it appears here and on your dashboard.
          </Card>
        ) : (
          <ul className="space-y-3">
            {announcementData.announcements.map((announcement) => (
              <li key={announcement._id}>
                <Card className="flex items-start gap-3 p-4">
                  <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-accent-400/14 text-accent-500">
                    <Megaphone className="h-4 w-4" />
                  </span>
                  <div className="min-w-0">
                    <p className="flex flex-wrap items-center gap-2 text-sm font-semibold text-ink">
                      {announcement.title}
                      <Badge tone={announcement.severity === 'warning' ? 'warning' : announcement.severity === 'danger' ? 'danger' : 'info'}>
                        {announcement.kind || 'notice'}
                      </Badge>
                    </p>
                    <p className="mt-1 text-xs leading-relaxed text-ink-muted">{announcement.body}</p>
                    <p className="mt-1 text-2xs text-ink-soft">
                      Published {formatRelative(announcement.publishedAt)}
                      {announcement.link && (
                        <>
                          {' · '}
                          <a href={announcement.link} className="cc-link" target="_blank" rel="noreferrer">
                            Learn more
                          </a>
                        </>
                      )}
                    </p>
                  </div>
                </Card>
              </li>
            ))}
          </ul>
        )}
      </section>

      <ConfirmDialog
        open={confirmClear}
        onClose={() => setConfirmClear(false)}
        onConfirm={() => clearAction.run()}
        loading={clearAction.isRunning}
        title="Clear read notifications?"
        message="This permanently removes notifications you have already read. Unread alerts stay in your list."
        confirmLabel="Clear read"
      />
    </>
  );
}
